//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daylon.RateMeApp.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daylon.RateMeApp.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string is not configured..
        /// </summary>
        public static string CONNECTION_STRING_UNCONFIGURED {
            get {
                return ResourceManager.GetString("CONNECTION_STRING_UNCONFIGURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite is required..
        /// </summary>
        public static string POST_FAVORITE_EMPTY {
            get {
                return ResourceManager.GetString("POST_FAVORITE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post with id {0} not found..
        /// </summary>
        public static string POST_ID_NO_FOUND {
            get {
                return ResourceManager.GetString("POST_ID_NO_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post no found..
        /// </summary>
        public static string POST_NO_FOUND {
            get {
                return ResourceManager.GetString("POST_NO_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedPost.Product is null..
        /// </summary>
        public static string POST_PRODUCT_EMPTY {
            get {
                return ResourceManager.GetString("POST_PRODUCT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id is required..
        /// </summary>
        public static string POST_PRODUCT_ID_EMPTY {
            get {
                return ResourceManager.GetString("POST_PRODUCT_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid category..
        /// </summary>
        public static string PRODUCT_CATEGORY_INVALID {
            get {
                return ResourceManager.GetString("PRODUCT_CATEGORY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid category is required..
        /// </summary>
        public static string PRODUCT_CATEGORY_INVALID_REQUIRED {
            get {
                return ResourceManager.GetString("PRODUCT_CATEGORY_INVALID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product description is required..
        /// </summary>
        public static string PRODUCT_DESCRIPTION_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_DESCRIPTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product description must no exceed 1000 characters..
        /// </summary>
        public static string PRODUCT_DESCRIPTION_MAX_LENGH {
            get {
                return ResourceManager.GetString("PRODUCT_DESCRIPTION_MAX_LENGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product id is required..
        /// </summary>
        public static string PRODUCT_ID_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product with id {0} not found..
        /// </summary>
        public static string PRODUCT_ID_NO_FOUND {
            get {
                return ResourceManager.GetString("PRODUCT_ID_NO_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name is required..
        /// </summary>
        public static string PRODUCT_NAME_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name must no exceed 200 characters..
        /// </summary>
        public static string PRODUCT_NAME_MAX_LENGH {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_MAX_LENGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products no found..
        /// </summary>
        public static string PRODUCT_NO_FOUND {
            get {
                return ResourceManager.GetString("PRODUCT_NO_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than zero..
        /// </summary>
        public static string PRODUCT_PRICE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("PRODUCT_PRICE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating must be between 0 and 5..
        /// </summary>
        public static string PRODUCT_RATING_LIMIT {
            get {
                return ResourceManager.GetString("PRODUCT_RATING_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sub category..
        /// </summary>
        public static string PRODUCT_SUB_CATEGORY_INVALID {
            get {
                return ResourceManager.GetString("PRODUCT_SUB_CATEGORY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid sub category is required..
        /// </summary>
        public static string PRODUCT_SUB_CATEGORY_INVALID_REQUIRED {
            get {
                return ResourceManager.GetString("PRODUCT_SUB_CATEGORY_INVALID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier personalized name is required when supplier option is indefinite..
        /// </summary>
        public static string PRODUCT_SUPPLIER_INVALID {
            get {
                return ResourceManager.GetString("PRODUCT_SUPPLIER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier personalized name must not exceed 200 characters..
        /// </summary>
        public static string PRODUCT_SUPPLIER_MAX_LENGH {
            get {
                return ResourceManager.GetString("PRODUCT_SUPPLIER_MAX_LENGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid supplier option..
        /// </summary>
        public static string PRODUCT_SUPPLIER_OPTIONS_INVALID {
            get {
                return ResourceManager.GetString("PRODUCT_SUPPLIER_OPTIONS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request data..
        /// </summary>
        public static string REQUEST_INVALID {
            get {
                return ResourceManager.GetString("REQUEST_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow Error..
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }
    }
}
